@startuml
scale 350 width

' in order to change this diagram, please got to http://www.planttext.com
skinparam state {
  StartColor Black
  EndColor Black
  BackgroundColor LightYellow
  BackgroundColor<<OrderIncomplete>> LightGreen
  BackgroundColor<<OrderProcessing>> LimeGreen
  BackgroundColor<<OrderProcessed>> Green
  BackgroundColor<<OrderErrored>> Red
  BorderColor Black
  FontName Impact
}
title Order State Model
state "1 - incomplete" as Incomplete <<OrderIncomplete>>
state "2 - processing" as Processing <<OrderProcessing>>
state "3 - processed" as Processed <<OrderProcessed>>
state "errored" as OrderErrored <<OrderErrored>>

state fork_state <<fork>>
[*] --> fork_state : POST /orders
fork_state ---> Incomplete : success
fork_state --> OrderErrored : prebooking failed
Incomplete -down-> Processing : 1st call to /order_items/{id}/book
Processing -down-> Processed : all orderItems are "confirmed"
Processed -down-> [*]

@enduml
